### ISSUE TITLE
Add quantifier and linear type systems

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#118]
Plan of attack after discussion with @wenkokke:

1. [x] Switch constraint solving to happen after every declaration, rather than at the very end of the file.
2. [x] Add implicit arguments to `Bool` type with quantifier annotations and add `HasForall`, `HasAnd`, `HasNeg` etc. type-classes
    - Unquantified
    - Forall
    - Exists
    - MixedParallel
    - MixedSequential
3. [x] Add implicit arguments to `Real` type with quantifier annotations:
    - Constant
    - Linear
    - NonLinear
4. [x] Any unsolved type metas or type-class constraints get automatically prepended to the type of the declaration.
5. [ ] Profit???

Problems not discussed in meeting:
 - `implicit parameter` declarations will generate meta-variables that are guaranteed to be unsolved at type-checking the declaration.... but the meta variable is at the expression level not the type level so maybe we can use that to disambiguate?

**Comment by wenkokke** [comment]
> * `implicit parameter` declarations will generate meta-variables that are guaranteed to be unsolved at type-checking the declaration.... but the meta variable is at the expression level not the type level so maybe we can use that to disambiguate?

Could you give an example?

**Comment by MatthewDaggitt** [comment]
For example:
```
implicit parameter n : Nat

preprocessDataset : Tensor Rat [ n , 20 ] -> Tensor Rat [ n , 20 ]
preprocessDataset = ....

dataset trainingInputs : Tensor Rat [ n , 20 ]
dataset trainingLabels : Tensor (Fin 5) [ n , 20 ]
```

The point of implicit parameter is to be able to globally declare parameters that are only known at compile time (in this case te size of the dataset, inferred from the dataset declarations). Internally the parameter declaration gets converted to a hole before type-checking, i.e.
```
n : Nat
n = _
```
which in turn gets converted to a meta during type-checking. The problem is that its value will only be solved after checking `trainingInputs`, and won't be solved after having checked `preprocessDataset`...

Hmm, this does get back to your original point that the error message if `trainingInputs` and `trainingLabels` differ in size is going to be bad. But we do need someway for the user to declare that they are the same, if currently unknown, size. Any thoughts @wenkokke ?

**Comment by wenkokke** [comment]
Right, so it’s a feature *designed* to take advantage of global constraint solving.

I’d say: 
- Implicit parameters should not be converted to meta variables, as their value won’t be known until runtime. Rather, we should treat them as module parameters, left as . abstract top-level definitions during type checking.
- Implicit parameters must be inferable from usage, i.e., if it’s used in a property, it must be used in the type of at least one dataset or network used in that property.

**Comment by MatthewDaggitt** [comment]
> Right, so it’s a feature designed to take advantage of global constraint solving.

Bingo.

> Implicit parameters must be inferable from usage, i.e., if it’s used in a property, it must be used in the type of at least one dataset or network used in that property.

Agreed.

> Implicit parameters should not be converted to meta variables, as their value won’t be known until runtime. Rather, we should treat them as module parameters, left as . abstract top-level definitions during type checking.

Hmm interesting. So currently we're loading in the datasets _before_ type-checking and using type-checking to ensure consistency with the implicit parameters (i.e. that the dataset sizes match), as well ensuring that the contents of the dataset match the given type (e.g. a dataset with type `Tensor (Fin 5) [10]` really does only contain the integers 0,1,2,3,4).

I guess if we treat the implicit arguments as abstract during type-checking, we then need to separate that step out into a second phase?

**Comment by wenkokke** [comment]
Wouldn’t we want to do type checking agnostic from datasets, so that we can use one file with multiple datasets, and can write them without having concrete datasets?

**Comment by MatthewDaggitt** [comment]
> Wouldn’t we want to do type checking agnostic from datasets, so that we can use one file with multiple datasets, and can write them without having concrete datasets?

Yes we probably do!

**Comment by MatthewDaggitt** [comment]
Linearity types and solver was added in b4833665992061f2a50ce8be6d56ade74ca51e3f and 612a036c1b7548996dfebf311265c64442958083, so closing this. The profit will have to wait.
