### ISSUE TITLE
Implement corresponding type-classes in Agda

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#120]
After [c90afa6](https://github.com/vehicle-lang/vehicle/commit/c90afa62b1a9ea50e1aaeeaab52471dd573704e3) we're now generating Agda code with type-classes in for declarations with no provided type. However the type-classes do not yet exist in our mini Agda library.

**Comment by wenkokke** [comment]
Could we simply instantiate the annotations with the unit type in Agda?

(We might need a different sort for annotations in vehicle to ensure that’s done safely, but that’s probably a good idea anyway.)

**Comment by MatthewDaggitt** [comment]
It's not the auxiliary annotations (polarity and linearity) that are the problem as they are removed after type-checking. It's the standard type-classes, e.g. `HasAdd`, `HasRatLiterals`

**Comment by MatthewDaggitt** [comment]
Added `HasAdd` and `HasSub` and have got rid of the need for the rest via a monomorphisation pass.
