### ISSUE TITLE
loss function tests - file does not exist

### ISSUE THREAD

**Issue by ndslusarz** [vehicle-lang/vehicle#160]
Error:
`          test\Vehicle\Test\CompileMode\Golden\simple-generalisedVariables\simple-generalisedVariables-temp-output.json: openFile: does not exist (No such file or directory)`

When trying to run:
`vehicle\test\specs\simple-untypedDecl.vcl`
`vehicle\test\specs\simple-arithmetic.vcl`
`vehicle\test\specs\simple-index.vcl`
`vehicle\test\specs\simple-generalisedVariables.vcl`

 for loss functions. For other tests the file gets created and written to without a problem.

**Comment by MatthewDaggitt** [comment]
Huh, this works fine for me. Going to have to look at what's going on on your computer?

**Comment by ndslusarz** [comment]
Funnily enough after testing now on the newly pulled repo it works fine for me as well. I suppose that means it was probably something unrelated on my side that was causing the problem but since I can't reproduce it anymore I can't find the cause.

**Comment by MatthewDaggitt** [comment]
Okay, well that's good I guess! Closing for now. Reopen this issue if it reoccurs.
