### ISSUE TITLE
Add the ability to pass command line options through to verifier

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#162]
Verifiers have a whole suite of command line options and the user may want to set some of them. We should add the ability for the user to pass the options through to verifier.

Will involve:
1. Adding a field to `VerifyOptions`
2. Using the contents of that field in the `invokeMarabou` method

**Comment by wenkokke** [comment]
We should name space these commands, and just pass them through as is, e.g., `--marabou-opts='<some stuff>'` should pass `<some stuff>` to Marabou.
