### ISSUE TITLE
windController example error

### ISSUE THREAD

**Issue by rdesmartin** [vehicle-lang/vehicle#166]
When running the command from the Readme file in `examples/windController`, I get the following error: `syntax error at line 12, column 1 before '#error'`, line 12 being a `@network` annotation.

**Comment by MatthewDaggitt** [comment]
Hmm so `windController` is in the test suite (which is passing), so it really should work! My first guess is that you've installed an out-of-date version of Vehicle, before we switched to the `@` annotation style. Have you pulled recently?

**Comment by rdesmartin** [comment]
I pulled tha last version and re-ran `cabal run build init` and `cabal install` and it seems to have fixed this error. However, now I get the following error from Marabou:
```
Marabou threw the following error:
  Network: examples/windController/controller.onnx
Caught a MarabouError error. Code: 105, Errno: 0, Message: Found input tensor in ONNX file with invalid size '0'.
```
When I examine the onnx file with netron (see below), it seems like the input layer has an unknown size, I don't know if this is linked.

![examine the onnx file with netron](https://user-images.githubusercontent.com/33431536/194892653-a03b6209-0f2c-4639-bf36-d6e4bd832b20.png)

**Comment by MatthewDaggitt** [comment]
Err okay, will investigate!

**Comment by MatthewDaggitt** [comment]
Fixed upstream in Marabou repo.
