### ISSUE TITLE
We actually do have recursion 

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#167]
Had thought that we didn't have recursion as we don't support forward references. Have just realised that because we have higher order functions, the user can implement recursion without them:
```
recFib : Nat -> (Nat -> Nat) -> Nat
recFib n f = if n < 2 then n else f (n-1) f + f (n-2) f

fib : Nat -> Nat
fib n = recFib n recFib 
```

Need to think through the consequences of this....

The first huge problem is that users can write non-terminating programs :sob:

**Comment by bobatkey** [comment]
The `recFib` function shouldn't type check. Its body treats `f` as if it had the type `Nat -> (Nat -> Nat) -> Nat` *and* `Nat -> Nat`.

**Comment by MatthewDaggitt** [comment]
Ah yes, you're right *doh*. I was in Python at the time I came across this, and forgot that it wouldn't type-check. Is there an easy proof that the Y-combinator is impossible to define in our language?

**Comment by bobatkey** [comment]
Looks to me like the definition of recFib shouldn't type check. `f` is used
as if it had type `Nat -> (Nat -> Nat) -> Nat` but the type of recFib says
it has type `Nat -> Nat`.
