### ISSUE TITLE
Test Suite (basic-tests) failing (agda tests)

### ISSUE THREAD

**Issue by Yiergot** [vehicle-lang/vehicle#170]
Seems to be checking against a hardcoded directory on a preset machine rather than the local proofcache

**Comment by MatthewDaggitt** [comment]
So we do try to remove filepaths from our tests:

https://github.com/vehicle-lang/vehicle/blob/ee04628af9c1dd3f8c5e69b79634cc8ad634bef9/test/Vehicle/Test/Utils/FilePath.hs#L15-L26

Clearly my regex is not working. Can you paste the example file paths here?

**Comment by MatthewDaggitt** [comment]
Ah sorry, already got them on Slack:

```
simple-triviallyTrue-Agda:          FAIL (1.44s)
         Output differs:26c26
         <    { proofCache  = "/home/matthew/Code/AISEC/vehicle/proofcache.vclp"
         ---
         >    { proofCache  = REDACTED TOP SECRET
         32c32
         <    { proofCache  = "/home/matthew/Code/AISEC/vehicle/proofcache.vclp"
         ---
         >    { proofCache  = REDACTED TOP SECRET

         Use -p '/simple-triviallyTrue-Agda/' to rerun this test only.
```

**Comment by MatthewDaggitt** [comment]
Looks like its the hyphen in the folder name....
