### ISSUE TITLE
Speed up of tests with parallelization 

### ISSUE THREAD

**Issue by Yiergot** [vehicle-lang/vehicle#176]
The test suite takes quite a long time to run each time - any chance the tests could be parallelized in `shake` similar to how it is done with make, e.g. `make -j 8`

**Comment by MatthewDaggitt** [comment]
Yup probably, though thinking about it the `acasXu` test takes over 80% of the time, so no matter how to parallelise it's not going to speed it up much.

**Comment by MatthewDaggitt** [comment]
Turns out tests are already parallelised which is what's causing my old laptop to crash when all the `acasXu` tests run concurrently :sweat_smile:
