### ISSUE TITLE
Ensure Python code is portable

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#179]
The Python bindings should be compatible with and tested with at least Python 3.7 - 3.11.

Ideally, our library would be compatible with the same version range as popular tools, e.g., TensorFlow, PyTorch, numpy, etc.

The easiest way to do this locally is to use PyEnv and Tox. We should also test on GitHub actions. For an example, we could look at [wenkokke/py-tree-sitter-talon](https://github.com/wenkokke/py-tree-sitter-talon), which is a Python package with native extensions, managed with Poetry.

**Comment by MatthewDaggitt** [comment]
Was fixed in v0.7.0
