### ISSUE TITLE
Add `requirements.txt` to Python code for reproducible builds

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#183]

**Comment by wenkokke** [comment]
I'd recommend managing dependencies with poetry instead:
https://python-poetry.org/

We'll have to move there at some point anyway, and it provides a lot more than just requirements: isolated builds, automated dependency bumps, packaging and distribution, etc.

Just running `poetry init` should get you a long way.

**Comment by wenkokke** [comment]
Related to #179

**Comment by MatthewDaggitt** [comment]
Ooh that does look nice! Have you used it before?

**Comment by wenkokke** [comment]
Yes, many times, see, e.g., the linked repository in the linked issue. 

(For one, it's one of the few ways I've actually managed a package with native extensions without drowning in deprecation warnings without implemented alternatives.)

**Comment by MatthewDaggitt** [comment]
We now have a working Python built pipeline so closing.
