### ISSUE TITLE
Extraneous constraint in Cabal file

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#190]
> Warning: The package has an extraneous version range for a dependency on an internal library: vehicle:vehicle-bnfc >=0 && ==0.1.0.1, vehicle >=0 && ==0.1.0.1, vehicle >=0 && ==0.1.0.1, vehicle >=0 && ==0.1.0.1, vehicle >=0 && ==0.1.0.1. This version range includes the current package but isn't needed as the current package's library will always be used.

**Comment by MatthewDaggitt** [comment]
When is this error being generated (i.e. what command are you running)? I'm guessing its originating from the `common common-test-base` and `executable vehicle` stanzas.

**Comment by MatthewDaggitt** [comment]
@wenkokke was this fixed in the project big refactor?

**Comment by wenkokke** [comment]
Yes.
