### ISSUE TITLE
Scope checking bug, causing type checking to fail

### ISSUE THREAD

**Issue by bobatkey** [vehicle-lang/vehicle#20]
The following vehicle code should type check:
```
network A : Type 0
network B : A -> Type 0

network fn : forall {x : A}. B x -> B x
```
However, it fails with:
```
Error: Could not solve the constraint: A ~ (B (i1)) (Line 4, Columns 39-40)
Fix: Check your types
```
Checking the debugging output, it seems that the problem is that something is going wrong with the names to de Bruijn conversion. The translation of the final line to core syntax with de Bruijn is:
```
(declare-network fn : (pi {x :type A} (pi (_ :type (B (i0))) (B (i0))))) 
```
but it ought to be:
```
(declare-network fn : (pi {x :type A} (pi (_ :type (B (i0))) (B (i1))))) 
```
(the last variable reference on the line ought to be `i1`, not `i0` which refers to the `B x` argument.

**Comment by MatthewDaggitt** [comment]
Thanks I'll look into it!

**Comment by MatthewDaggitt** [comment]
In my infinite wisdom we weren't adding machine names to the context :facepalm: Now fixed.
