### ISSUE TITLE
Remove top level `vehicle.cabal` file

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#201]
I'm guessing this isn't needed any more?

https://github.com/vehicle-lang/vehicle/blob/dev/vehicle.cabal

**Comment by wenkokke** [comment]
This is a result of the automatic merge.

**Comment by MatthewDaggitt** [comment]
Closed with [b7dfeef](https://github.com/vehicle-lang/vehicle/pull/204/commits/b7dfeef866626b2c321b676a9e486037d2e7737a)
