### ISSUE TITLE
`hie.yaml` is broken?

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#202]
All the components appear to be commented out? Probably shouldn't be.

My editor support in VSCode is completely nixed in all the subprojects.

**Comment by wenkokke** [comment]
Almost certainly due to #201

**Comment by wenkokke** [comment]
I'll add some hie-yaml tests.

**Comment by MatthewDaggitt** [comment]
> Almost certainly due to https://github.com/vehicle-lang/vehicle/issues/201

Unfortunately even after removing it, editor support is still broken. Why is so much of `hie.yaml` commented out?

**Comment by MatthewDaggitt** [comment]
Error:

> Failed to find the GHC version of this Cabal project.
Error when calling cabal exec -v0 -- ghc --print-libdir

**Comment by wenkokke** [comment]
> > Almost certainly due to #201
> 
> Unfortunately even after removing it, editor support is still broken. Why is so much of `hie.yaml` commented out?

Because it wasn’t needed, since it’s inferred via the .cabal file.

**Comment by MatthewDaggitt** [comment]
Fixed by reverting Cabal version in `vehicle.cabal` to 3.4

**Comment by wenkokke** [comment]
Yeah, that fix was also part of the `expand-ci` PR.

**Comment by MatthewDaggitt** [comment]
Is that merged? It's not merged right? So we definitely shouldn't close it!

**Comment by wenkokke** [comment]
> Fixed by reverting Cabal version in `vehicle.cabal` to 3.4

I assumed you'd fixed it

**Comment by MatthewDaggitt** [comment]
No, I'm still blocked from committing by https://github.com/vehicle-lang/vehicle/issues/208!! Your fix `SKIP=prettier git commit -m "<message>" or git commit -m "<message>" --no-verify` doesn't seem to work for me.

**Comment by MatthewDaggitt** [comment]
So would appreciate it if you could strip the `prettier` dependency out and merge that in :+1:

**Comment by MatthewDaggitt** [comment]
Fixed with [38aaf17](https://github.com/vehicle-lang/vehicle/commit/38aaf17df700a72b9e800b9fd9b78e82a33d90dd)
