### ISSUE TITLE
`ReadTheDocs` documentation doesn't seem to build automatically

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#203]
Annoyingly I have to go and hit build manually as described in `HACKING.md`....

**Comment by wenkokke** [comment]
How did it used to build automatically?

**Comment by wenkokke** [comment]
I'll add this hook later today:
https://github.com/thclark/pre-commit-sphinx

**Comment by MatthewDaggitt** [comment]
When I cloned the example project from ReadTheDocs it did build automatically...

**Comment by MatthewDaggitt** [comment]
But we really want it to build on the `ReadTheDocs` servers, not locally. It's not that the build is failing, its that it never triggers.

**Comment by wenkokke** [comment]
You’ll have to give me access to the readthedocs integration.

**Comment by MatthewDaggitt** [comment]
Email address you'd like to use?

**Comment by MatthewDaggitt** [comment]
I've added you @wenkokke, but managed to fix it myself. I had to "resync the webhook" whatever that means...
