### ISSUE TITLE
Rename golden test files so they have the file extension at the end.

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#209]
By naming them e.g. `X.json.golden` it prevents JSON syntax highlighting from firing. Maybe we should rename them to `X.golden.json`?

**Comment by wenkokke** [comment]
That makes it significantly harder to ensure Git and pre-commit don't touch them.

Also, they're golden files, do we need syntax highlighting?

**Comment by MatthewDaggitt** [comment]
> That makes it significantly harder to ensure Git and pre-commit don't touch them.

How come? Can't we just match on `.golden.json` rather than `.golden`? 

> Also, they're golden files, do we need syntax highlighting?

Yes, for example we've been viewing the generated test JSON files in @ndslusarz's PhD supervisions. Not having syntax highlighting is annoying.

**Comment by MatthewDaggitt** [comment]
Decided this is not that important, and can always be configured manually in the IDE, so closing.
