### ISSUE TITLE
Golden test framework doesn't detect errors at all.

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#216]
If I replace the following line:

https://github.com/vehicle-lang/vehicle/blob/f60140e7eca7e9a4e42729f8088a06277ca34767/vehicle/src/Vehicle/Compile.hs#L146

with `compilerDeveloper "whoops"` which should cause every single golden test to fail, then I still get all golden tests passing.

This isn't great for a golden test suite....

**Comment by MatthewDaggitt** [comment]
Okay so the first bug is at 

https://github.com/vehicle-lang/vehicle/blob/59c9c21895f26155438d5793e4d277c3a4991e49/vehicle/tests/golden/Vehicle/Test/Golden/TestSpec.hs#L207

which should be `not $ null messages`.

Fixing that results in every single test failing though :sob: Debugging continues...

**Comment by MatthewDaggitt** [comment]
Okay, the next thing is that `toTestTree` isn't removing the `needs` files from the list of files in the temporary output directory.

**Comment by MatthewDaggitt** [comment]
And the `readGoldenFiles` isn't stripping off the `.golden` file file extension before compiling them to the produced output files.

**Comment by MatthewDaggitt** [comment]
and `readGoldenFiles` is erroneously appending `testDirectory` twice to the golden file path.

**Comment by MatthewDaggitt** [comment]
A load of error tests have been changed from `Marabou` to `TypeCheck`. The errors don't get thrown during type-checking, they occur after type-checking, after the parameter values are loaded in so...

**Comment by MatthewDaggitt** [comment]
Backticks have been erroneously introduced into the golden files for the `unparsableX` numeric tests.

**Comment by MatthewDaggitt** [comment]
Output file names have been changed to not have the `output` suffix in the Agda tests, but the golden files have not been updated.

**Comment by MatthewDaggitt** [comment]
A lot of the file paths in the golden error tests have been made relative, but the file paths in the golden files have not been updated

**Comment by MatthewDaggitt** [comment]
All proof cache locations have been dropped from the Agda golden tests.

**Comment by MatthewDaggitt** [comment]
And it looks like the broken test suit allowed several bugs to slip through in f60140e7eca7e9a4e42729f8088a06277ca34767, 4c75a6af6b834bf5126fb14d5401ecac696e2c0e, 59c9c21895f26155438d5793e4d277c3a4991e49.

**Comment by MatthewDaggitt** [comment]
Okay I'm reverting the above 3 commits until the test suite is operation again.

**Comment by MatthewDaggitt** [comment]
`prune-decls` golden test is missing the command line argument to actually do the pruning.

**Comment by MatthewDaggitt** [comment]
Fixed all the above in [173a1b7](https://github.com/vehicle-lang/vehicle/commit/173a1b755533e7cb94e414a40d00ad01eca9c22f)

**Comment by wenkokke** [comment]
Oof, I’m sorry, that’s a lot of bugs.
