### ISSUE TITLE
New golden test system does not handle logging well at all.

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#218]
You can't enable logging because it gets caught on the standard output stream and therefore causes the tests to fail. Makes it very difficult to debug tests.

**Comment by wenkokke** [comment]
Shouldn’t logging go to standard error? Can we redirect logging to a file, and then print that file at the end?

**Comment by MatthewDaggitt** [comment]
Okay after discussing this in person, I'm resigned to the fact that this is the best we can get without a lot of effort.
