### ISSUE TITLE
Improving prettiness of writing multiple parameters in vcl

### ISSUE THREAD

**Issue by Tgl70** [vehicle-lang/vehicle#245]
Currently to write multiple parameters you have to do something like:
```
@parameter
param1 : Type
@parameter
param2 : Type
@parameter
param3 : Type
```
I think it would be nice in cases where you want to define multiple parameters one after the other to have something like:
```
@parameters
param1 : Type
param2 : Type
param3 : Type
```

**Comment by wenkokke** [comment]
That's, unfortunately, ambiguous. If we're indentation sensitive, we could add the option for an indented block after `@parameter`, though?

**Comment by MatthewDaggitt** [comment]
Or we alternatively we could be empty line sensitive?

**Comment by wenkokke** [comment]
That's not something easily supported by BNFC, not do I think any other language does it, so it might be more confusing for users?

**Comment by MatthewDaggitt** [comment]
Hmm how bad is this scaling problem actually? I think this is only worth it if we have situations where we actually want a significant number of parameters in a row? In which case, there's a strong argument that you might want to pass them using a dataset instead?

**Comment by MatthewDaggitt** [comment]
Marking this as `wontfix` as I don't think the solution of adding indentation sensitivity is worth the accompany gain. For small numbers of parameters, I think having individual declarations is clearer. Fro large numbers of parameters, the `@dataset` mechanism should be used anyway.
