### ISSUE TITLE
Adjust version bounds for `numpy` and `tensorflow`

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#269]
The current `pyproject.toml` for `vehicle-python` sets the version bounds for `numpy` and `tensorflow` at *the latest minor version or higher*, but they can almost certainly be lowered.

We should see what functions from these libraries are used and see what versions that restricts us to.

**Comment by MatthewDaggitt** [comment]
@wenkokke what's the status on this? We no longer use `numpy`. Have we got precise bounds for `tensorflow`?

**Comment by wenkokke** [comment]
One could say overly precise.
