### ISSUE TITLE
Extend normalization with an allow/block list

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#29]
Different backends may or may not support different operators, so it would be a good idea to extend the normalization algorithm to optionally normalize/not normalize certain built-ins (or even defined functions￼).

**Comment by MatthewDaggitt** [comment]
Agreed, it's been on my to-do list for a while but it's a lot of refactoring :smile:

**Comment by MatthewDaggitt** [comment]
As part of this we should separate out negation and quantification juggling into a separate pass, as these don't rely on using DeBruijn indices.

**Comment by MatthewDaggitt** [comment]
Hmm just googled it and it's not really called "juggling" and that makes me sad :cry:

**Comment by MatthewDaggitt** [comment]
This was done at some point in the unspecificed past. There's now a `NormalisationOptions` class that allows the caller to configure what gets normalised.
