### ISSUE TITLE
Write binary interface files

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#302]
We should migrate our interface files to versioned binary files using [Data.Binary](https://hackage.haskell.org/package/binary-0.10.0.0/docs/Data-Binary.html).

**Comment by MatthewDaggitt** [comment]
Just tried this on branch [`binary-object-files`](https://github.com/vehicle-lang/vehicle/tree/binary-object-files). Get the following error when decoding the files:
```
vehicle: Data.Binary.Get.runGet at position 2022: Unknown encoding for constructor
          CallStack (from HasCallStack):
           error, called at libraries/binary/src/Data/Binary/Get.hs:345:5 in binary-0.8.9.0:Data.Binary.Get
```

Might be related to https://github.com/kolmodin/binary/pull/175? I don't think we have 256 constructor objects, but `Builtin` probably has 256 nested constructors in total?

**Comment by MatthewDaggitt** [comment]
Dodged the issue by switching to the competitor `cereal` which seems to work fine and gives us the expected big performance boost when deserialising.
