### ISSUE TITLE
275% performance drop

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#331]
The recent commit 5386b68fe3026362f1ea22035db7dc3e88471f9b introducing strictness and no thunks increased the time required to run the test suite from ~2 seconds on my high-specs laptop to 7.5 seconds. This is moderately disastrous as it can't easily be backed out again without also backing out [ca99b8d](https://github.com/vehicle-lang/vehicle/commit/ca99b8da9e5aabde2c94b758bb4141fbe53ebed5).

As I think I mentioned in the chat before, we really shouldn't be making any performance changes that aren't clearly cutting out code execution without a working benchmark suite.

**Comment by wenkokke** [comment]
We can simply remove the bangs and leave the other changes intact.

**Comment by wenkokke** [comment]
I'm having trouble finding a performance regression. If anything, there's a slight improvement.

## benchmark 78508913bd1104468dd161db2729f6e5739f2472

```
Benchmark 1: cabal test all
  Time (mean ± σ):     19.570 s ±  0.129 s    [User: 16.862 s, System: 3.403 s]
  Range (min … max):   19.333 s … 19.766 s    10 runs
```

## benchmark `benchmark-before`

Includes #330, #332, and #334.

```
Benchmark 1: cabal test all
  Time (mean ± σ):     20.030 s ±  0.118 s    [User: 16.982 s, System: 3.342 s]
  Range (min … max):   19.917 s … 20.301 s    10 runs
```

## benchmark `benchmark-before-hasmap`

Includes #330 and #334.

```
Benchmark 1: cabal test all
  Time (mean ± σ):     20.043 s ±  0.100 s    [User: 16.967 s, System: 3.324 s]
  Range (min … max):   19.955 s … 20.240 s    10 runs
```

## benchmark `benchmark-after`

Includes #315, #330,  #334.

```
Benchmark 1: cabal test all
  Time (mean ± σ):     19.298 s ±  0.082 s    [User: 16.361 s, System: 3.333 s]
  Range (min … max):   19.174 s … 19.440 s    10 runs
```

**Comment by wenkokke** [comment]
I'm not sure if it's strictness & nothunks, but there's definitely a performance hit in the past few commits:

### benchmark 78508913bd1104468dd161db2729f6e5739f2472
```
Benchmark 1: cabal test all
  Time (mean ± σ):      9.671 s ±  0.056 s    [User: 27.081 s, System: 4.919 s]
  Range (min … max):    9.596 s …  9.758 s    10 runs
```

After running ormolu on 78508913bd1104468dd161db2729f6e5739f2472:

```
Benchmark 1: cabal test all
  Time (mean ± σ):      9.735 s ±  0.061 s    [User: 27.125 s, System: 5.005 s]
  Range (min … max):    9.664 s …  9.861 s    10 runs
```

**Comment by wenkokke** [comment]
After running ormolu:

```
Benchmark 1: cabal test all
  Time (mean ± σ):      9.735 s ±  0.061 s    [User: 27.125 s, System: 5.005 s]
  Range (min … max):    9.664 s …  9.861 s    10 runs
```

**Comment by wenkokke** [comment]
Fixe by #341

**Comment by MatthewDaggitt** [comment]
Unfortunately this wasn't fixed for me by #341. At commit c94dbb26585db6adb661d714efdb32bff39e6a7e, the situation is now significantly worse. 

- Prior to 5386b68fe3026362f1ea22035db7dc3e88471f9b (i.e. before any strictness changes occured) it took 2.5 seconds on my laptop.
- After 5386b68fe3026362f1ea22035db7dc3e88471f9b it took ~7 seconds.
- After c94dbb26585db6adb661d714efdb32bff39e6a7e it now takes ~23 seconds on my laptop to run!

**Comment by wenkokke** [comment]
This is quite confusing, because for me nothing changed?!

**Comment by wenkokke** [comment]
Do you mean that c94dbb26585db6adb661d714efdb32bff39e6a7e specifically worsened performance, because that doesn't even touch any code.

**Comment by wenkokke** [comment]
Could you determine the exact commit where the performance regression happens for you, using the benchmark script, e.g., by running:
```bash
git checkout 7dce91468e97dc47c36317f6df8cad08021a1c31 && ./scripts/benchmark
git checkout 4a80e1e9bd793cfe533632196ad5606ec8258609 && ./scripts/benchmark
git checkout d627895271dab8fec5921c5706b3e456586ae04b && ./scripts/benchmark
git checkout 3d5350decf66ac3633ce184eb83975ae2bca32f3 && ./scripts/benchmark
git checkout 13db5647c278132f24da38aca6bc605828ca6ac7 && ./scripts/benchmark
git checkout 9377d9e3fc986d54d6523be4854cc72e433a776a && ./scripts/benchmark
git checkout 19ad7f54e125375b99ca515030fbd94fe06c0caf && ./scripts/benchmark
git checkout 43757ba63d5cf09c1b0eb0bafc47e17c763c9889 && ./scripts/benchmark
git checkout c94dbb26585db6adb661d714efdb32bff39e6a7e && ./scripts/benchmark
git checkout c4c29174b1168948c4f569e9cc265fb794c56ffa && ./scripts/benchmark
git checkout 0c6b9163b0ec66c95080db397c845db752432cea && ./scripts/benchmark
git checkout 32825535a0dfa8ca9e53056093fa13f693be4e7d && ./scripts/benchmark
```

**Comment by MatthewDaggitt** [comment]
I get the following timings so it looks like its 4a80e1e9bd793cfe533632196ad5606ec8258609 responsible:
```
git checkout 7dce91468e97dc47c36317f6df8cad08021a1c31 && ./scripts/benchmark     4.042 s ±  0.053 s
git checkout 4a80e1e9bd793cfe533632196ad5606ec8258609 && ./scripts/benchmark    27.301 s ±  2.592 s
git checkout d627895271dab8fec5921c5706b3e456586ae04b && ./scripts/benchmark    27.684 s ±  2.568 s
git checkout 3d5350decf66ac3633ce184eb83975ae2bca32f3 && ./scripts/benchmark    28.962 s ±  2.111 s
git checkout 13db5647c278132f24da38aca6bc605828ca6ac7 && ./scripts/benchmark
git checkout 9377d9e3fc986d54d6523be4854cc72e433a776a && ./scripts/benchmark
git checkout 19ad7f54e125375b99ca515030fbd94fe06c0caf && ./scripts/benchmark    28.824 s ±  2.342 s
git checkout 43757ba63d5cf09c1b0eb0bafc47e17c763c9889 && ./scripts/benchmark
git checkout c94dbb26585db6adb661d714efdb32bff39e6a7e && ./scripts/benchmark
git checkout c4c29174b1168948c4f569e9cc265fb794c56ffa && ./scripts/benchmark
git checkout 0c6b9163b0ec66c95080db397c845db752432cea && ./scripts/benchmark
git checkout 32825535a0dfa8ca9e53056093fa13f693be4e7d && ./scripts/benchmark    27.984 s ±  2.241 s
```

**Comment by wenkokke** [comment]
Here's my timings, using the histogram plotter in #349

![Figure_1](https://user-images.githubusercontent.com/3983973/210152858-f228653d-57c5-4ed5-8a10-7429aa6463b7.png)

**Comment by MatthewDaggitt** [comment]
Fixed by https://github.com/vehicle-lang/vehicle/pull/348
