### ISSUE TITLE
Fold parsing rules for TypeClass into Expr

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#35]

**Comment by MatthewDaggitt** [comment]
At the moment the parsing rules for `TypeClasses` live in their own BNFC class.

https://github.com/wenkokke/vehicle/blob/600e200491fab1920e394b3c62aed108640a5af8/src/bnfc/Frontend.cf#L98

We would like to fold them into the `Expr` class instead at level 15, e.g.

https://github.com/wenkokke/vehicle/blob/600e200491fab1920e394b3c62aed108640a5af8/src/bnfc/Frontend.cf#L123

Once the grammar is updated then you will need to run `make bnfc` to regenerate the corresponding Haskell files and then edit the file where we elaborate from the BNFC AST to the core Vehicle AST:

https://github.com/wenkokke/vehicle/blob/600e200491fab1920e394b3c62aed108640a5af8/src/hs/Vehicle/Language/Elaborate/Frontend.hs#L126

You can test the changes haven't broken anything by running `make test`.
