### ISSUE TITLE
Generalize the getter type classes using a trick from WGP'14

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#41]
We can generalize our getter type classes using the following code:
```Haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}

import Data.Proxy (Proxy(..))

data Pos = Here | Left Pos | Right Pos

type family Elem (a :: *) (b :: *) :: Maybe Pos where
  Elem a a      = 'Just 'Here
  Elem a (l, r) = Choose (Elem a l) (Elem a r)
  Elem a b      = 'Nothing

type family Choose (l :: Maybe a) (r :: Maybe a) :: Maybe a where
  Choose ('Just x) _         = 'Just x
  Choose _         ('Just y) = 'Just y
  Choose _         _         = 'Nothing

class Get (mp :: Maybe Pos) (a :: *) (b :: *) where
  get :: Proxy p -> a -> b

instance Get (Just Here) a a where
  get _p a = a

instance Get (Just p) a b => Get (Just (Left p)) a (b, c) where
  get _p (b, c) = get Proxy b

instance Get (Just p) a c => Get (Just (Right p) a (b, c) where
  get _p (b, c) = get Proxy c

type Has a b = Get (Elem a b) a b
```
This should let us define classes such as `HasProvenance` in a way that doesn't restrict them to being strictly left or right biased, and which happens to also generalize over the type that we are getting.

Some adaptation may be required to let this search through the AST.

The trick is taken from the following paper:
- https://dl.acm.org/doi/10.1145/2633628.2633635
- https://www.youtube.com/watch?v=OqybbwYpnuw

**Comment by MatthewDaggitt** [comment]
On balance, I don't think that this increased level of abstraction is justified by the benefits it results in. Haven't had any problems with left/right bias, and we already have solutions that generalise over the type we're getting.

Going to close this for the moment, but can reopen if the problems outlined above arise.
