### ISSUE TITLE
Sort out naming of the two types of cons symbols

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#443]
At the moment:
- List type constructor `::`
- Vector type function `::v`

Maybe `cons` and `::`? 

Then add to CHANGELOG.

**Comment by wenkokke** [comment]
Why can't we use a type class to overload `::`, and then have the builtin symbols be `::List` and `::Vec`?

**Comment by MatthewDaggitt** [comment]
Cons vector is removed in #636
