### ISSUE TITLE
Loss function translation does not handle named variables and named types

### ISSUE THREAD

**Issue by ndslusarz** [vehicle-lang/vehicle#472]
When encountering any sort of named variable declaration in a `.vcl` file the loss function translation throws an error. For example starting from simplest example if we put :

```
epsilon : Rat
epsilon = 0.01
```
and then attempt to use it in one of the constraints in the file it will produce an error: `Exception: Problem during compilation: encountered unexpected expression 'epsilon' during compilation to loss functions.`. For a different example (with different error although I believe these used to be analogous at the time I discovered this error for the first time so the cause is likely the same or related, but I might be wrong) if we have:

```
type Image = Tensor Rat [28, 28]

@network
mnist : Image -> Vector Rat 10
```

this will cause error `Exception: Problem during compilation: encountered unexpected expression 'Rat' during compilation to loss functions. `. If we use 
```
@network
mnist : Tensor Rat [28, 28] -> Vector Rat 10
```
The program will compile normally. All those examples come from the `mnist.vcl` spec if one wanted to reproduce them easily.

**Comment by MatthewDaggitt** [comment]
Fixed by recent refactoring of loss function implementation.
