### ISSUE TITLE
Hide redirect options using `internal`

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#488]

**Comment by MatthewDaggitt** [comment]
Can you provide a little more detail about this? Hide them where and with what mechanism?

**Comment by wenkokke** [comment]
The library we're using for command line options has the ability to mark an option as "internal" or "hidden" which influence if/how they show up in the output of `--help`:
https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:hidden

As they're not meant to be user-facing, I think we should mark them as such.
