### ISSUE TITLE
Release version of Vehicle versioning not working

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#537]
I ran:
```
pip install vehicle-lang
vehicle --version
```
and got
```
0.3.0+b11752b
```

This suggests the cabal `release-build` flag is not being set properly?

**Comment by wenkokke** [comment]
It's not, because there's no release workflow on GitHub at the present.

**Comment by MatthewDaggitt** [comment]
Ah right, that explains it! Which script does the distribution to `PyPy`?

**Comment by wenkokke** [comment]
> Ah right, that explains it! Which script does the distribution to `PyPy`?

Me.

**Comment by wenkokke** [comment]
Trusted publishers from GitHub now work, so I'll actually write a script now.

**Comment by wenkokke** [comment]
Fixed.
