### ISSUE TITLE
Vehicle executable installed via `pip` seems to not be outputting on `stdout`

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#544]
If you run `pip install vehicle-lang` and then run `vehicle --version` on the command line you get `0.3.3` printed. So far so good.

However, this output doesn't seem to actually be on standard out. If you pipe `stdout` into a file by running `vehicle --version > logfile` then the resulting file `logfile` is completely empty. This is a big problem for Agda integration which relies on stdout.

This appears to be an artefact of building the executable for distribution as if you run `cabal run exe:vehicle -- --version > logfile` then `logfile` contains the correct contents.

@wenkokke any thoughts about what might be the problem here?

**Comment by wenkokke** [comment]
This is probably some very obscure stuff?
It couldn't hurt to ask the Haskell mailing list or the GHC developers what exactly is going on here.

**Comment by MatthewDaggitt** [comment]
This was fixed in https://github.com/vehicle-lang/vehicle/commit/1cdf17390adf19da22561a8191a71a1686738608
