### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#553]
@wenkokke what's the procedure for cutting a new release?

**Comment by wenkokke** [comment]
1. Ensure all work is committed and you're on dev.

2. Run the tests:
  ```
  # from the repository root
  cabal test all
  # from py-vehicle-lang
  tox
  ```

3.  Run the following command, using `--patch`, `--minor`, or `--major` as needed:
  ```
  pipx run bumpver update --patch --dry
  ```
  That'll print a diff.

4. If the diff looks good, rerun the previous command without `--dry`.

### Dependencies

To run the BumpVer command, you need either pipx (recommended) or BumpVer. If you don't have [pipx](https://pypi.org/project/pipx/), either install it or simply install bumpver globally with `pip install bumpver` and omit `pipx run` from the command.

To run the Python tests you need to have the reference GHC release installed, which is currently GHC 9.4.4.
You also need [Tox](https://tox.wiki/en/latest/) and [PyEnv](https://github.com/pyenv/pyenv), and an installed version of every supported Python release. At the time of writing, that's 3.7 to 3.11, so you run:
```
pyenv install 3.7 3.8 3.9 3.10 3.11
```
If you have all that, tox takes care of the rest, and will build and test Vehicle with GHC 9.4.4 and each of these Python releases.

**Comment by wenkokke** [comment]
Guess we should just move my reply to CONTRIBUTING.md?
