### ISSUE TITLE
Sort assertions before outputting queries

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#591]
At the moment, our golden file tests are very sensitive to the compilation internals as if the order of the assertions get switched the test fails. One way of fixing this would be to do a lexicographic sort over the sparse assertions before compiling them down to the final verifier.

**Comment by wenkokke** [comment]
It seems strange to add this behavior, not for any benefit of the end user, just to not have up update the golden tests as often?

**Comment by MatthewDaggitt** [comment]
Well as a a retroactive justification we could use it to detect duplicate queries? :wink: 

I'm not sure that just because it doesn't benefit the end user, it shouldn't be done? The problem is not that the updating of the tests per se, it's detecting whether there's been an actual change to the output beyond just a reordering of assertions in the file. For the MNIST spec for example, it involves eyeballing whether two 2800 line files are permutations of each other? :smile:

**Comment by MatthewDaggitt** [comment]
Looking at the changes to the robustness queries in https://github.com/vehicle-lang/vehicle/pull/660/files is an excellent example of why this would be nice to have!
