### ISSUE TITLE
"Trivial" is not the most descriptive message

### ISSUE THREAD

**Issue by BenCoke12** [vehicle-lang/vehicle#612]
An alternative message could be: "Trivial: Vehicle did not need to call the verifier."

**Comment by MatthewDaggitt** [comment]
Hmm, how about a little shorter "Trivial: no need to call verifier"?

**Comment by BenCoke12** [comment]
Yeah, I think that's good. Just an assurance of what trivial means.

**Comment by wenkokke** [comment]
Shouldn't this message mirror whatever the output of the verify command is?

**Comment by MatthewDaggitt** [comment]
This _is_ the output of the verify command!

**Comment by wenkokke** [comment]
This doesn't also occur with the compile command? 

Either way, I meant shouldn't we have this match whatever the output is from a successful call to Marabou?

**Comment by MatthewDaggitt** [comment]
In #705 I've gone one better than this and added an actual warning at compilation time when this problem is detected that contains far more detail. I've therefore left the message at verification time as is.

**Comment by wenkokke** [comment]
Fixed by #705.
