### ISSUE TITLE
Implication when evaluating network

### ISSUE THREAD

**Issue by BenCoke12** [vehicle-lang/vehicle#642]
The property: 
```
let scores = classifier (images ! 0) in
    scores ! 7 > scores ! 2  => scores ! 7 > scores ! 2
```

produces "proved no witness exists" on test images. This should be "witness found" in all cases as A => A is true for all values of A. When run with [0,0,0,0,0,0,0,0,0,0] in the place of `classifier (images ! 0)` the result is  🗸  - (trivial).
The code is:

```
numberOfClasses = 10
type Class = Index numberOfClasses

type Image = Tensor Rat [28, 28]

type Score = Rat

@network
classifier : Image -> Vector Score numberOfClasses

@dataset
images : Vector Image 1

@property
pulloverLowScore : Bool
pulloverLowScore = 
    let scores = classifier (images ! 0) in
    scores ! 7 > scores ! 2  => scores ! 7 > scores ! 2
```

**Comment by wenkokke** [comment]
What is the Vehicle command you're running with this? What images are you using?

**Comment by wenkokke** [comment]
Is the test in 32f49e0 representative of the issue you're having?

**Comment by BenCoke12** [comment]
The vehicle command I used is verify:

`vehicle verify --specification vclspecs/debugging.vcl --network classifier:onnxnetworks/fashion1l32n.onnx --dataset images:idxdata/individuals/Image9.idx --verifier Marabou --verifierLocation ../Marabou/build/Marabou`

I've been testing on the images in the fashion test set. debugging.vcl is the code above. The code in the test is representative of the issue. I don't understand how the test will run if the network used is fake though.

**Comment by wenkokke** [comment]
It won't, I'll need an actual network for that. The `test.json` file has the command for the test, and at the moment it only uses a `compile` command.

**Comment by BenCoke12** [comment]
Network is here: https://github.com/BenCoke12/FashionVerification/blob/main/onnxnetworks/fashion1l32n.onnx
Data is this: https://github.com/BenCoke12/FashionVerification/blob/main/idxdata/individuals/Image0.idx
Specification is this: https://github.com/BenCoke12/FashionVerification/blob/main/vclspecs/debugging.vcl

The command I used is: `vehicle verify --specification vclspecs/debugging.vcl --network classifier:onnxnetworks/fashion1l32n.onnx --dataset images:idxdata/individuals/Image1.idx --verifier Marabou --verifierLocation ../Marabou/build/Marabou`

The expected result is: result: 🗸  - witness found
The actual result is: result: ✗ - proved no witness exists

**Comment by MatthewDaggitt** [comment]
Caused by same bug as #641
