### ISSUE TITLE
`forallIndex` seems to take a `Nat` rather than an index?

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#647]
Here's some Python generated from MNIST:
```python
def validImage(x):
    return forallIndex(
        __vehicle__.Nat(28),
        (
        ...
        ),
    )
```
This will result in errors if the interpretations of `Index` and `Nat` deviate, such as when using numpy.

**Comment by MatthewDaggitt** [comment]
@wenkokke isn't this by design? The definition in the standard library takes a `Nat` as it's first argument:

https://github.com/vehicle-lang/vehicle/blob/469d0f9c0977954a2568e06030f2a6749399a155/vehicle/lib/std.vcl#L57-L58

I don't think this is a bug in the translation?
