### ISSUE TITLE
Robustness counterexamples are not within specified epsilon

### ISSUE THREAD

**Issue by BenCoke12** [vehicle-lang/vehicle#649]
Counterexamples generated do not fit the specification.

Specification: https://github.com/BenCoke12/FashionVerification/blob/main/vclspecs/fashionRobustness.vcl
Network: https://github.com/BenCoke12/FashionVerification/blob/main/onnxnetworks/fashion1l32n.onnx
Image dataset: https://github.com/BenCoke12/FashionVerification/blob/main/idxdata/individuals/Image104.idx
Label dataset: https://github.com/BenCoke12/FashionVerification/blob/main/idxdata/individuals/Label104.idx
Epsilon: 0.05

Command: vehicle verify --specification vclspecs/fashionRobustness.vcl --network classifier:onnxnetworks/fashion1l32n.onnx --dataset imageDataset:idxdata/individuals/Image104.idx --dataset labelDataset:idxdata/individuals/Label104.idx --parameter epsilon:0.05 --verifier Marabou --verifierLocation ../Marabou/build/Marabou

Counterexample generated: https://github.com/BenCoke12/FashionVerification/blob/main/tools/counterexample.txt
Testing script: https://github.com/BenCoke12/FashionVerification/blob/main/tools/testingScript.py
Script result: 
```
Not equal to tolerance rtol=0, atol=0.051

Mismatched elements: 251 / 784 (32%)
Max absolute difference: 1.05
Max relative difference: 51.47792395
```

Expected script result: Passing the assert

**Comment by MatthewDaggitt** [comment]
@BenCoke12, could you have a look at the queries generated for the image and see whether they look correct? You can have a look at them via the `compile` command (see the documentation on `Verifying a specification`). You should be able to work which query is returning SAT by when the command `verify` command finishes.

**Comment by BenCoke12** [comment]
It looks like it gets through 6/9 queries. In the 7th query there are many like this:
```
x188 >= -0.05
x188 <= 0.05
```
 which looks like epsilon bounds. There are also many like:
```
x188 <= 0.0
x188 >= -1.0
```
which I'm not sure what they are, maybe something to do with valid image (though that should be between 0 and 1 not -1). And more with other bounds like:
```
x304 >= -0.03431372549019608
x304 <= 0.06568627450980392
```
