### ISSUE TITLE
Unable to infer type of bound variable error with a robust property

### ISSUE THREAD

**Issue by kiczaaa** [vehicle-lang/vehicle#662]
Specification: https://github.com/kiczaaa/verification/blob/main/iris_final/iris.vcl
Network: https://github.com/kiczaaa/verification/blob/main/iris_final/network.onnx
Input dataset: https://github.com/kiczaaa/verification/blob/main/iris_final/iris_x.idx
Label dataset: https://github.com/kiczaaa/verification/blob/main/iris_final/iris_y.idx
Epsilon: 0.1

Command: vehicle verify --specification iris.vcl --network irisClassifier:network.onnx --dataset trainingX:iris_x.idx --dataset trainingY:iris_y.idx --parameter epsilon:0.1 --verifier Marabou

Output: Error at Line 5, Columns 27-30: Unable to infer type of bound variable
Fix: add more type annotations

The error appears only when the spec has `normalCorr` function and `robust` property at the same time. So, `normalCorr` works fine only when I have property1, but after I add robust property, the error appears. I found that when I disaalbe `normalCorr` part, then it works again.

**Comment by MatthewDaggitt** [comment]
You've said that counter-examples don't fit the specifications, but given that the spec doesn't compile in the first place, I assume you don't mean that @kiczaaa ?

**Comment by kiczaaa** [comment]
Oh sorry, that's from the post I copied from for the structure. 
Counter examples are not the case for this one.

**Comment by MatthewDaggitt** [comment]
Hi @kiczaaa, just looking at this now. Unfortunately when I run the command you posted, no error appears. I can't quite replicate the problem from the description:

> The error appears only when the spec has normalCorr function and robust property at the same time. So, normalCorr works fine only when I have property1, but after I add robust property, the error appears. I found that when I disaalbe normalCorr part, then it works again.

Please could you post the exact contents of the specification file that causes the error below?

**Comment by MatthewDaggitt** [comment]
Looking at the error message and it's location, I strongly suspect this was an instance of https://github.com/vehicle-lang/vehicle/issues/700...

**Comment by MatthewDaggitt** [comment]
Going to close this as #700 was merged in and @kiczaaa has finished her project I think.
