### ISSUE TITLE
Robustness counterexamples are not violations of the property

### ISSUE THREAD

**Issue by BenCoke12** [vehicle-lang/vehicle#663]
The robustness property states: 
```
boundedByEpsilon perturbation and validImage perturbedImage =>
		advises perturbedImage label
```
this should find a counterexample if and only if;
the perturbation is within epsilon (0.05) distance from the original image and 
the perturbed image is a valid image (pixel values are between 0 and 1) and
the classifier does not choose the original label.

Two counterexamples are generated from this specification (by switching the "-" to a "+" on line 32). The first does not meet any of the criteria, the second only meets the last point.

Specification: https://github.com/BenCoke12/FashionVerification/blob/main/vclspecs/fashionRobustness.vcl
Network: https://github.com/BenCoke12/FashionVerification/blob/main/onnxnetworks/fashion1l32n.onnx
Image dataset: https://github.com/BenCoke12/FashionVerification/blob/main/idxdata/individuals/Image104.idx
Label dataset: https://github.com/BenCoke12/FashionVerification/blob/main/idxdata/individuals/Label104.idx
Epsilon: 0.05

Command:

`vehicle verify --specification vclspecs/fashionRobustness.vcl --network classifier:onnxnetworks/fashion1l32n.onnx --dataset imageDataset:idxdata/individuals/Image104.idx --dataset labelDataset:idxdata/individuals/Label104.idx --parameter epsilon:0.05 --verifier Marabou --verifierLocation ../Marabou/build/Marabou`

Testing script (with counterexamples included): https://github.com/BenCoke12/FashionVerification/blob/main/tools/testCe.py

Script result for counterexample 1: 
```
Valid image criterion satisfied on all pixels:  False
Within epsilon distance:  False
Original image predicted label:  7
Counterexample predicted label:  7
True Label:  7
...
AssertionError:
Not equal to tolerance rtol=0, atol=0.05001

Mismatched elements: 263 / 784 (33.5%)
Max absolute difference: 1.
Max relative difference: 43.21329668
```
Script result for counterexample 2: 
```
Valid image criterion satisfied on all pixels:  False
Within epsilon distance:  False
Original image predicted label:  7
Counterexample predicted label:  5
True Label:  7
...
AssertionError:
Not equal to tolerance rtol=0, atol=0.05001

Mismatched elements: 251 / 784 (32%)
Max absolute difference: 1.05
Max relative difference: 45.21329668
```

Expected result: 
True for the first two properties and a difference between the counterexample predicted label and the true label.

**Comment by MatthewDaggitt** [comment]
As discussed in the Slack message, the counter-example script at https://github.com/BenCoke12/FashionVerification/blob/main/tools/testCe.py is wrong. There is no bug here.
