### ISSUE TITLE
Sort out what we're doing with user "sequence literals"

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#68]
At the moment, the user can construct tensors using the syntax `[a, b, c]`. Likewise, the user can use `[a, b, c]` to also construct a list. However lists can also be constructed using the syntax `a :: b :: c :: []`. Under the hood `[....]` is represented by the `LSeq [Expr]` constructor, and eventually as @wenkokke points out, we'll want to change the Haskell list type to something that supports efficient vector operations. Because the `LSeq` constructor is used to represent multiple different types,  necessarily it has to store the type-class it belongs to as well and the type-checking pass for it is... messy. The `::` syntax is represented a set of builtin `Cons` operators.

However, this also means we have two different possible forms for lists in the AST. This makes it very difficult to pattern match on them, as you have to pattern match on both the `Seq` form and the `Cons` form. This is rearing it's head when I'm trying to implement #61.
So ideally we need only a single representation for lists in the AST.

Now there are several ways we can go about doing this:

1. Desugar list `Seq`s to `Cons` before type-checking during the desugaring pass.
  - Advantages: Can remove the type-class argument in `LSeq` constructor. Very clean implementation of type-checking.
  - Disadvantages: As before type-checking desugaring must be syntax directed, so we need different user syntax for list and tensor literals. Perhaps `[ ... ]` and `<| ... |>`?
  
 2. Desugar list `Seq`s to `Cons` during type-checking
   - Advantages: Can remove the type-class argument in `LSeq` constructor. Can keep the same user syntax `[...]` for both lists and tensors.
   - Disadvantages: Actually changing the form of the AST during type-checking, as opposed to merely inserting extra nodes, seems... aesthetically unpleasing!

3. Normalise list `Seq`s to `Cons` after type-checking during the normalisation pass.
   - Advantages: Can keep the same user syntax `[...]` for both lists and tensors
   - Disadvantages: Have to keep the type-class argument in `LSeq` constructor.

I'm leaning towards 2 myself. @bobatkey / @wenkokke do you see any other alternatives?

**Comment by MatthewDaggitt** [comment]
With 1. my second preference and 3. my least preferred. Actually 1. and 2. are much of a muchness in my mind. Not the end of the world to make the user specify tensors using different syntax from lists.

**Comment by wenkokke** [comment]
I would suggest keeping both representations and not desugaring. The sequence liberals are not complete since the remainder of the list cannot be a thunk, the conses are less efficient.

**Comment by MatthewDaggitt** [comment]
Thanks @wenkokke so I think you're a bit confused about what we currently have? Currently `Cons` only works for `List`s, so `Tensor`s are already incomplete. It's impossible to have the same `Cons` constructor work for both `List` and `Tensor` right, because they have very different types even with type-class support? So we'd have to disambiguate the cons internally anyway. 

Therefore I view that as a mostly orthogonal issue to the one I describe above, which is a problem with having two different representations for `List`s. Is your argument that we should have two separate internal representations for both `List`s and `Tensor`s? I was hoping that we'd reduce `List` to only having one internal representation...

**Comment by wenkokke** [comment]
I think that the best option would be to keep two different separate internal representations for lists — for the reasons I’ve outlined above — and perhaps simply write some pattern syntax to help you match?

**Comment by MatthewDaggitt** [comment]
Fixed in [c7dada8](https://github.com/vehicle-lang/vehicle/commit/c7dada8853bde6de5dc85b7f817d751aad291eb8). As @wenkokke suggested, now have two different internal representation for lists and vectors. `List`s are created via `cons`/`nil` and `Vector`s by the `LVec` constructor. Coercion functions from the frontend `[ x, y, z ]` syntax are automatically inserted during elaboration.
