### ISSUE TITLE
Outdated documentation of external tests

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#715]
The documentation states:

> Some golden tests require external tools, such as the MarabouVerify test above. To run these tests, add --test-option="--external=<external>" to the test command, where <external> is the name of the external dependency, such as Marabou.

However after the latest golden option refactoring, the `--external` option is no longer recognised....

**Comment by MatthewDaggitt** [comment]
This is blocking me from adding new tests. I've also tried the new `--test-option="--allowlist-externals Marabou"` but that is giving me the same `Invalid option `--allowlist-externals Marabou'` error.

As is `--test-option="--allowlist-externals [Marabou]"`

**Comment by wenkokke** [comment]
Where do the square brackets come from?It should be:
`--test-option="--allowlist-externals=Marabou"`

**Comment by MatthewDaggitt** [comment]
Okay thanks that worked.

The square brackets came from me trying to infer from the fact there was `list` in the option name. Why is the name so complicated? Can we turn it back to `externals` or something similar?
