### ISSUE TITLE
Add `CITATION.cff`

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#781]
See file format:
https://github.com/citation-file-format/citation-file-format#readme

Possibilities for minting DOIs for software:
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by MatthewDaggitt** [comment]
Yup was planning to wait until the Vehicle tool paper was published and then add that as the main citation?

**Comment by wenkokke** [comment]
The purpose is that the main citation should be the software itself, and we can mint DOIs for the software versions.

We can add all Vehicle papers as reference works, which should show up as well, and once the tool paper is out we can put that as the _preferred_ reference work.
