### ISSUE TITLE
More name suggestions

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#81]
Not going to let this one die:

- Vehicle
- GardAI? (gardai = Irish police officer)
- ensure/ennsure/eNNsure?
- SpecAI?
- Specify?
- Intend/inntend/iNNtend/iNteNd?

**Comment by wenkokke** [comment]
“Vehicle” sounds good, has a nice ring to it!

**Comment by Yiergot** [comment]
You know what would be a great idea, since the aim of the tool is to make AI Secure and Explainable by Construction, it could be "AISEC" or "AISEC-tool"

**Comment by MatthewDaggitt** [comment]
Published work on it, so....
