### ISSUE TITLE
Support for timeout

### ISSUE THREAD

**Issue by tflinkow** [vehicle-lang/vehicle#869]
Vehicle doesn't currently seem to support specifying a timeout for verification (or at least I didn't find it in the docs), so I've tried to use `--verifier-args "--timeout=120"`.

I'm not sure what Marabou returns exactly (unknown? timeout?) but it is something Vehicle doesn't expect:

```
Verifying properties:
  robust!0 [.......................................................] 0/1 queries

Error: Unexpected output from the Marabou verifier. Cannot find 'sat' or 'unsat'
```

I could work around that, but unfortunately, when trying to verify a property on more than one image, verification will not continue afterwards. 

Expected behaviour would be an option for / handling of something like "verify this property on x images, with a timeout of y seconds for each".

**Comment by MatthewDaggitt** [comment]
Yup that seems like a serious problem. I'll get that fixed and try and push out a new version today or tomorrow.

**Comment by MatthewDaggitt** [comment]
Hmm looking at this, I can't even seem to get Marabou to timeout properly:

Running this in the Vehicle top-level folder: 
```
Marabou examples/mnist-robustness/mnist-classifier.onnx vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust\!0-query2.txt.golden --timeout=1
```
results in no timeout.

**Comment by MatthewDaggitt** [comment]
Any ideas what I'm doing wrong @tflinkow ?

**Comment by wenkokke** [comment]
> Hmm looking at this, I can't even seem to get Marabou to timeout properly:
> 
> 
> 
> Running this in the Vehicle top-level folder: 
> 
> ```
> 
> Marabou examples/mnist-robustness/mnist-classifier.onnx vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust\!0-query2.txt.golden --timeout=1
> 
> ```
> 
> results in no timeout.

The obvious question is how long that query normally runs (i.e. less than 1s?) which I'm sure you thought of.

My guess is that if this isn't an API problem, it might be a race condition which fails to timeout if the value is too low.

**Comment by MatthewDaggitt** [comment]
> The obvious question is how long that query normally runs (i.e. less than 1s?) which I'm sure you thought of.

It actually runs way longer than it usually runs, and then Marabou runs out of memory :confused: 

That seems like a reasonable guess. I'll open an issue on the Marabou repo at some point.

**Comment by tflinkow** [comment]
> Hmm looking at this, I can't even seem to get Marabou to timeout properly:
> 
> Running this in the Vehicle top-level folder:
> 
> ```
> Marabou examples/mnist-robustness/mnist-classifier.onnx vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust\!0-query2.txt.golden --timeout=1
> ```
> 
> results in no timeout.

Apologies, should have specified: I think --timeout is a Marabou v2 option, on Marabou v1 it's --timeoutInSeconds.

If that doesn't work I'll send my query and network file later; that definitely times out.
