### ISSUE TITLE
Allow user to specify which function generates loss function & normalisation

### ISSUE THREAD

**Issue by ndslusarz** [vehicle-lang/vehicle#97]
--functionName 

We need to stop full normalisation. Will require some normalisation (declaration substitution has to happen inside the function but we do need the name of the one generating loss)

Annotations - not meaningfull, get rid of in translation
Let - we want them normalised out (could keep them in but performance gain not worth added complexity)
Lam - can't be normalised, needs to be translated and put into JSON

Important: Loss functions can ONLY be generated if the function goes to Prop/Bool. Otherwise we need to throw an error.

**Comment by MatthewDaggitt** [comment]
Hmm I think all these things have been done so now closing.
